### ISSUE TITLE
Flow does not detect errors on Object

### ISSUE THREAD

**Issue by SimonDegraeve** [gcanti/flow-io#11]
Flow should throw with something like `boolean. This type is incompatible with string`.

``` js
import * as t from 'flow-runtime';
import type { TypeOf } from 'flow-runtime';

const Obj = t.object({
  key: t.string,
});

type ObjT = TypeOf<typeof Obj>;

const obj: ObjT = {
  key: false,
};
```

PS: I know the library is still at an early stage but I really like the approach. Nice work.

**Comment by gcanti** [comment]
Hi, thanks for reporting. It's a bummer, seems a bug

``` js
type ObjT = $ObjMap<{ key: string }, <T>(v: T) => T>;

const obj: ObjT = {
  key: 1 // <= no error here...
}

// ...but this is ok
;(obj.key: string)
// ...and this raises an error
;(obj.key: number)
```

/cc @vkurchatkin

**Comment by vkurchatkin** [comment]
Something weird with literal assignment, indeed:

``` js
type ObjT = $ObjMap<{ key: string }, <T>(v: T) => T>;

declare var x: { key: number }; 
const obj: ObjT = x;
```

Definitely worth reporting

**Comment by vkurchatkin** [comment]
It seems that you can write anything to `key`:

``` js
type ObjT = $ObjMap<{ key: string }, <T>(v: T) => T>;

declare var obj: ObjT

obj.key = 1;
obj.key = {};
obj.key = true;
```

**Comment by gcanti** [comment]
@SimonDegraeve not sure if you are still interested but the upstream bug is fixed now.

Instead of duplicating the code, I'm working on a Flow definition file for io-ts (https://github.com/gcanti/io-ts/pull/89)

If you want to try it out you can `npm i io-ts@next` and then somewhere in your project

```js
import * as t from 'io-ts'

const Person = t.type({
  name: t.string,
  age: t.number
})

type PersonT = t.TypeOf<typeof Person>

const person1: PersonT = {
  name: 'foo',
  age: 43
}
const person2: PersonT = {
  name: 'foo',
  age: 'bar' // static error
}
```
